// Generated by LiveScript 1.3.1
(function(){
  var getsecret, bonusly, fs, API_KEY, b;
  getsecret = require('getsecret');
  bonusly = require('bonusly');
  fs = require('fs');
  API_KEY = getsecret('bonusly_api_key');
  b = new bonusly(API_KEY);
  b.bonuses.getAll({}).then(function(results){
    console.log(results);
    fs.writeFileSync('bonusly_data.json', JSON.stringify(results, null, 2));
    return console.log('done writing');
  });
}).call(this);
